[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"
  NPM_FLAGS = "--include=dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Enable App Router support
    experimental = { appDir = true }

[dev]
  command = "npm run dev"
  port = 3000

# Redirect rules
[[redirects]]
  from = "/dashboard"
  to = "/login"
  status = 302

# Next.js App Router API routes - remove this redirect to let Next.js handle API routes
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"